### ISSUE TITLE
I'll try soon man

### ISSUE THREAD

**Issue by AndrevMask** [nurdiny13/LENOVO-IDEAPAD-GAMING-3i-Hackintosh-Opencore#1]
You are crazy. You're awesome dude. Now the catalina is downloading and our device is the same, I only have 256 SSD 1TB HDD disk. I found it worked the touchpad and fixed the sleep problem. We will try, thank you.

**Comment by AndrevMask** [comment]
> You are crazy. You're awesome dude. Now the catalina is downloading and our device is the same, I only have 256 SSD 1TB HDD disk. I found it worked the touchpad and fixed the sleep problem. We will try, thank you.

Unfortunately, my friend, I failed. I opened the Verbose mode and examined it, it hangs and does not open. this is my device https://pcsupport.lenovo.com/en/en/products/laptops-and-netbooks/3-series/ideapad-gaming-3-15imh05/81y4?linkTrack=Homepage%3ABody_Search%20Products&searchType=4&keyWordSearch=ideapad%20Gaming% 203-15IMH05%20Laptop%20%20Type%2081Y4 Can you help?

**Comment by nurdiny13** [comment]
can you show me the last error message in verbose mode?
can you screenshot the contents of your kext and acpi folders?

**Comment by AndrevMask** [comment]
> can you show me the last error message in verbose mode?
> can you screenshot the contents of your kext and acpi folders?

I wrote you on telegram. I'll try again tonight or tomorrow on behalf of username nurdiny13. I'll post the details, man.
