### ISSUE TITLE
Unable to boot opencore

### ISSUE THREAD

**Issue by mir-mehdi** [nurdiny13/LENOVO-IDEAPAD-GAMING-3i-Hackintosh-Opencore#4]
I’m sure I followed right steps from dortania’s guide but still was unable to boot open core. Showed me this error(look at the attachment)
My specs are:
IdeaPad Gaming 3 15IMH05
Intel(R) Core(TM) i5-10300H CPU @ 2.50GHZ
Nvidia GTX 1650
![5541B10B-AA67-453E-AB8E-45EE2598E1CD](https://user-images.githubusercontent.com/75182113/143274112-6e05490b-b0fa-422f-8c1d-420aabcab992.jpeg)

**Comment by nurdiny13** [comment]
please clone this repo again, there are new additional files & boot folders.
can you screenshoot your directory efi on flashdisk

**Comment by mir-mehdi** [comment]
> please clone this repo again, there are new additional files & boot folders.
> can you screenshoot your directory efi on flashdisk

I’m not home but I’ll do it as soon as I get home. Thank you so much for the support!🙏🏻
