### ISSUE TITLE
unable to activate FaceTime....

### ISSUE THREAD

**Issue by mir-mehdi** [nurdiny13/LENOVO-IDEAPAD-GAMING-3i-Hackintosh-Opencore#5]
it says, an error occurred.

**Comment by nurdiny13** [comment]
please generate your own smbios.
follow this guide and using "MacBookPro16,1"
https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html
https://www.tonymacx86.com/threads/create-unique-system-board-serial-numbers-with-gensmbios-video-tutorial.308444/
